const test=require('node:test');const assert=require('node:assert/strict');const {deliverNotification,isRecipientAllowed,notificationMode}=require('../dist/services/notification-delivery.service');
const response=(ok,body={id:'provider-id'})=>({ok,json:async()=>body});
test('les trois modes sont explicites',()=>{for(const mode of ['sandbox','test_live','production'])assert.equal(notificationMode({NOTIFICATION_MODE:mode}),mode);assert.throws(()=>notificationMode({NOTIFICATION_MODE:'unsafe'}))});
test('Mailtrap Sandbox non configuré reste PREPARED',async()=>{const result=await deliverNotification({channel:'email',to:'dev@example.test',text:'Message'},{environment:{NOTIFICATION_MODE:'sandbox'}});assert.equal(result.status,'PREPARED');assert.equal(result.provider,'mailtrap')});
test('SMS local est SIMULATED sans faux envoi',async()=>{const result=await deliverNotification({channel:'sms',to:'+243810000000',text:'Message'},{environment:{NOTIFICATION_MODE:'sandbox'}});assert.equal(result.status,'SIMULATED');assert.equal(result.provider,'simulated')});
test('test_live bloque tout destinataire hors liste blanche',async()=>{let called=false;const result=await deliverNotification({channel:'email',to:'user@example.com',text:'Message'},{environment:{NOTIFICATION_MODE:'test_live',NOTIFICATION_TEST_EMAIL_ALLOWLIST:'qa@example.com',RESEND_API_KEY:'secret',NOTIFICATION_EMAIL_FROM:'noreply@example.com'},fetcher:async()=>{called=true;return response(true)}});assert.equal(result.status,'PREPARED');assert.equal(result.reason,'recipient_not_allowed');assert.equal(called,false)});
test('test_live préfixe email et SMS autorisés',async()=>{const bodies=[];const fetcher=async(_url,options)=>{bodies.push(JSON.parse(options.body));return response(true,{id:'accepted',messages:[{messageId:'sms-id',status:{groupName:'PENDING'}}]})};await deliverNotification({channel:'email',to:'QA@Example.com',subject:'Sujet',text:'Texte'},{environment:{NOTIFICATION_MODE:'test_live',NOTIFICATION_TEST_EMAIL_ALLOWLIST:'qa@example.com',RESEND_API_KEY:'key',NOTIFICATION_EMAIL_FROM:'from@example.com'},fetcher});await deliverNotification({channel:'sms',to:'+243 810 000 000',text:'Texte'},{environment:{NOTIFICATION_MODE:'test_live',NOTIFICATION_TEST_PHONE_ALLOWLIST:'+243810000000',INFOBIP_API_KEY:'key',INFOBIP_BASE_URL:'https://example.api',INFOBIP_SMS_FROM:'PEDAGO'},fetcher});assert.match(bodies[0].subject,/^\[TEST PEDAGO CONTROL\]/);assert.match(bodies[0].text,/^\[TEST PEDAGO CONTROL\]/);assert.match(bodies[1].messages[0].text,/^\[TEST PEDAGO CONTROL\]/)});
test('un fournisseur refusant ne produit jamais SENT',async()=>{const result=await deliverNotification({channel:'email',to:'qa@example.com',text:'Message'},{environment:{NOTIFICATION_MODE:'production',RESEND_API_KEY:'key',NOTIFICATION_EMAIL_FROM:'from@example.com'},fetcher:async()=>response(false)});assert.equal(result.status,'FAILED');assert.notEqual(result.status,'SENT')});
test('aucun résultat ne contient clé API OTP ou token',async()=>{const result=await deliverNotification({channel:'sms',to:'+243810000000',text:'Code confidentiel'},{environment:{NOTIFICATION_MODE:'production',INFOBIP_API_KEY:'top-secret',INFOBIP_BASE_URL:'https://example.api',INFOBIP_SMS_FROM:'PEDAGO'},fetcher:async()=>response(true,{messages:[{messageId:'safe-id',status:{groupName:'PENDING'}}]})});const serialized=JSON.stringify(result);assert.doesNotMatch(serialized,/top-secret|Code confidentiel|token/i);assert.equal(result.status,'SENT')});
