const test=require('node:test'),assert=require('node:assert/strict'),{readFileSync}=require('node:fs'),{join}=require('node:path'),{Decimal}=require('@prisma/client/runtime/library');const read=p=>readFileSync(join(__dirname,'..',p),'utf8');
test('la prise en charge école produit un solde Parent nul',()=>{const service=read('src/services/parent-contribution.service.ts');assert.match(service,/mode==='PRIS_EN_CHARGE_PAR_ECOLE'\?new Prisma\.Decimal\(0\)/);assert.match(service,/status:covered\?'PRIS_EN_CHARGE'/)});
test('une échéance mensuelle conserve tous les snapshots',()=>{const schema=read('prisma/schema.prisma'),service=read('src/services/parent-contribution.service.ts');for(const field of['mode_snapshot','amount_due','amount_paid','balance','grace_days_snapshot','reminder_days_snapshot'])assert.ok(schema.includes(field));assert.match(service,/uq_parent_contribution_student_period|P2002/)});
test('paiements partiel et total mettent à jour solde et statut',()=>{const service=read('src/services/parent-contribution.service.ts');assert.match(service,/paid\.equals\(due\.amount_due\)\?'EN_REGLE':'PARTIEL'/);assert.match(service,/balance:due\.amount_due\.sub\(paid\)/);assert.match(service,/parent_contribution_payments\.create/)});
test('jours restants et retard tiennent compte du délai de grâce',()=>{const service=read('src/services/parent-contribution.service.ts');assert.match(service,/grace\.setUTCDate/);assert.match(service,/days_remaining:Math\.ceil/)});
test('historique immuable sans recalcul des anciennes échéances',()=>{const service=read('src/services/parent-contribution.service.ts');const payment=service.slice(service.indexOf('recordContributionPayment'),service.indexOf('ownContributions'));assert.match(payment,/parent_contribution_dues\.update\(\{where:\{id:due\.id\},data:\{amount_paid:paid,balance:/);assert.doesNotMatch(payment,/data:\{amount_due:|data:\{mode_snapshot:/);assert.doesNotMatch(service,/parent_contribution_payments\.(update|delete)/)});
test('Parent limité aux enfants approuvés de son guardian',()=>{const service=read('src/services/parent-contribution.service.ts');assert.match(service,/guardian_id:guardian\.id,status:'active',validated_at:\{not:null\}/)});
test('permissions et isolation refusent Informaticien et autre école',()=>{const routes=read('src/routes/parent-contribution.routes.ts'),seed=read('src/seed/access.seed.ts');assert.match(routes,/requireSchoolScope\(\)/);const tech=seed.match(/const technicianPermissions = \[([\s\S]*?)\] as const/)?.[1]||'';assert.doesNotMatch(tech,/CONTRIBUTION/);assert.match(routes,/requireRole\('PARENT'\)/);assert.match(routes,/requireRole\('SUPER_ADMIN'\)/)});
test('DTO externes utilisent public_id sans identifiants internes',()=>{const service=read('src/services/parent-contribution.service.ts');assert.match(service,/public_id:d\.public_id/);const dto=service.slice(service.indexOf('export const dueDto'),service.indexOf('/** Enregistre'));for(const field of['school_id','student_id','setting_id','due_id','recorded_by_user_id'])assert.doesNotMatch(dto,new RegExp(field))});
