import { useState } from 'react'
import { apiErrorMessage } from '../../services/api'
import { adminParentalApi, type Guardian } from '../../services/adminParental'

const maskEmail=(value:string)=>{const [local,domain]=value.split('@');return domain?`${local.slice(0,2)}***@${domain}`:'Contact masqué'}
const maskPhone=(value:string)=>{const digits=value.replace(/\D/g,'');return digits.length>4?`*** *** ${digits.slice(-4)}`:'Contact masqué'}

/** Une invitation préparée n'est pas un envoi réussi : le fournisseur de livraison reste distinct. */
export function InvitationPanel({schoolId,guardian}:{schoolId:string;guardian:Guardian}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[result,setResult]=useState<{expiresAt:Date}|null>(null);const contact=guardian.email?maskEmail(guardian.email):guardian.phone?maskPhone(guardian.phone):'Contact indisponible';const prepare=async()=>{if(busy)return;setBusy(true);setError('');try{const response=await adminParentalApi.prepareInvitation(schoolId,guardian.public_id);setResult({expiresAt:new Date(Date.now()+response.expires_in_minutes*60_000)})}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}};return <section className="admin-card resource-form" style={{marginTop:14}}><h2>Créer ou préparer le compte Parent</h2><p>Contact vérifié utilisé : <strong>{contact}</strong></p><p>Le canal est déterminé par le contact vérifié et les préférences enregistrées. Aucun mot de passe n’est choisi par l’Admin.</p>{error&&<div className="admin-error">{error}</div>}{result&&<div className="resource-success"><strong>Invitation préparée, envoi automatique non configuré.</strong><p>Expiration prévue : {result.expiresAt.toLocaleString('fr-FR')}</p><p>Une réémission invalide automatiquement l’ancienne invitation.</p></div>}<button className="admin-button purple" disabled={busy||(!guardian.email&&!guardian.phone)} onClick={()=>void prepare()}>{busy?'Préparation…':result?'Réémettre l’invitation':'Préparer l’invitation'}</button></section>}
