import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { useAuth } from '../../../auth'
import { adminParentalApi, studentTrackingLabel, type Student } from '../../../services/adminParental'
import { PageHeader } from '../../../components/adminParental/PageHeader'
import { ResourceState } from '../../../components/adminParental/ResourceState'
import { StatusBadge } from '../../../components/adminParental/StatusBadge'

export function StudentProfilePage(){const {publicId}=useParams();const{user}=useAuth();const[data,setData]=useState<Student|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const load=()=>{if(!user?.school_id||!publicId)return;setLoading(true);void adminParentalApi.student(user.school_id,publicId).then(r=>setData(r.student)).catch(e=>setError(e instanceof Error?e.message:'Erreur API')).finally(()=>setLoading(false))};useEffect(load,[user?.school_id,publicId]);const toggle=async()=>{if(!data||!user?.school_id||!publicId)return;if(!confirm(`${data.enrollment?.parental_tracking_enabled?'Désactiver':'Activer'} le Suivi parental pour cet élève ?`))return;setSaving(true);try{const r=await adminParentalApi.setTracking(user.school_id,publicId,!data.enrollment?.parental_tracking_enabled);setData(r.student)}catch(e){setError(e instanceof Error?e.message:'Modification impossible')}finally{setSaving(false)}};return <><PageHeader icon="←" title="Profil de l’élève" subtitle="Consultez toutes les informations détaillées de l’élève." back="/admin/eleves"/><ResourceState loading={loading} error={error} empty={!data} retry={load}>{data&&<><section className="admin-card resource-profile"><div className="resource-profile-head"><span className="resource-avatar">{data.first_name[0]}{data.last_name[0]}</span><div><h2>{data.last_name} {data.middle_name} {data.first_name}</h2><StatusBadge status={data.status}/></div><div className="admin-actions"><button className="admin-button secondary" disabled={saving} onClick={()=>void toggle()}>{saving?'Enregistrement…':data.enrollment?.parental_tracking_enabled?'Désactiver le suivi':'Activer le suivi'}</button></div></div><div className="resource-profile-grid"><section><h3>Informations générales</h3><dl><dt>Matricule</dt><dd>{data.matricule||'—'}</dd><dt>Date de naissance</dt><dd>{data.birth_date?new Date(data.birth_date).toLocaleDateString('fr-FR'):'—'}</dd><dt>Sexe</dt><dd>{data.gender||'—'}</dd></dl></section><section><h3>Scolarité</h3><dl><dt>Classe actuelle</dt><dd>{data.enrollment?.academic_year_classes?.school_classes?.name||'—'}</dd><dt>Année scolaire</dt><dd>{data.enrollment?.academic_year_classes?.academic_years?.name||'—'}</dd><dt>Suivi parental</dt><dd><StatusBadge status={studentTrackingLabel(data)}/></dd></dl></section><section><h3>Informations personnelles</h3><dl><dt>Lieu de naissance</dt><dd>{data.birth_place||'—'}</dd><dt>Adresse</dt><dd>{data.address||'—'}</dd></dl></section></div></section><div className="resource-tabs"><span>Informations générales</span><span>Scolarité</span><span>Présences</span><span>Documents</span><span>Historique</span></div></>}</ResourceState></>}
