import test from 'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{canAccessPath}from'../src/auth/routePolicy.ts';
const root=resolve(import.meta.dirname,'..');const src=(p:string)=>readFileSync(resolve(root,p),'utf8');const app=src('src/App.tsx');const service=src('src/services/adminParental.ts');
test('resource routes are ADMIN_GESTIONNAIRE only',()=>{for(const path of ['/admin/eleves','/admin/eleves/nouveau','/admin/eleves/opaque-id','/admin/parents','/admin/parents/opaque-id/enfants','/admin/rattachements/demandes']){assert.equal(canAccessPath(path,['ADMIN_GESTIONNAIRE']),true);assert.equal(canAccessPath(path,['PARENT']),false)}})
test('student list, creation and profile use secured API service',()=>{assert.match(service,/async students/);assert.match(service,/createStudent:/);assert.match(service,/student: \(/);assert.match(app,/StudentListPage/);assert.match(app,/StudentFormPage/);assert.match(app,/StudentProfilePage/)})
test('scheduled parental tracking status is supported',()=>{assert.match(service,/tracking_status\?: 'Inactif' \| 'Programmé' \| 'Actif'/);assert.match(src('src/components/adminParental/StatusBadge.tsx'),/programm/)})
test('guardian creation and attached children are implemented',()=>{assert.match(service,/createGuardian:/);const profile=src('src/pages/admin/guardians/GuardianProfile.tsx');assert.match(profile,/student_guardians/);assert.match(profile,/link.status==='active'/)})
test('non-approved child links never expose a profile link',()=>{const profile=src('src/pages/admin/guardians/GuardianProfile.tsx');assert.match(profile,/link.status==='active'&&child\?\.public_id/);assert.match(profile,/Accès non accordé/)})
test('attachment wizard submits only the existing direct link API',()=>{const wizard=src('src/pages/admin/attachments/AttachWizard.tsx');assert.match(wizard,/attachStudent/);assert.match(wizard,/Confirmer le rattachement/);assert.match(wizard,/ne crée pas une demande « En attente »/)})
test('missing attachment-request API is disclosed without fake approval',()=>{const requests=src('src/pages/admin/attachments/AttachmentRequests.tsx');assert.match(requests,/aucune route pour lister, soumettre, approuver ou refuser/);assert.match(requests,/disabled>Approuver/);assert.match(requests,/Refuser avec motif/)})
test('public IDs are used in all new resource URLs',()=>{assert.match(app,/eleves\/:publicId/);assert.match(app,/parents\/:publicId/);assert.match(app,/demandes\/:publicId/);assert.doesNotMatch(app,/eleves\/:id/);assert.match(service,/encodeURIComponent\(publicId\)/)})
test('resource screens implement loading error empty and success states',()=>{const state=src('src/components/adminParental/ResourceState.tsx');assert.match(state,/if \(loading\)/);assert.match(state,/if \(error\)/);assert.match(state,/if \(empty\)/);assert.match(src('src/pages/admin/attachments/AttachWizard.tsx'),/resource-success/)})
test('OTP copy does not claim to validate parentage',()=>{const form=src('src/pages/admin/guardians/GuardianForm.tsx');assert.match(form,/OTP confirme uniquement/);assert.match(form,/ne valide jamais automatiquement le lien de parenté/)})
