import test from 'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{canAccessPath}from'../src/auth/routePolicy.ts';
const root=resolve(import.meta.dirname,'..');const src=(p:string)=>readFileSync(resolve(root,p),'utf8');const app=src('src/App.tsx');const service=src('src/services/adminParental.ts');const requests=src('src/pages/admin/attachments/AttachmentRequests.tsx');
test('resource routes are ADMIN_GESTIONNAIRE only',()=>{for(const path of ['/admin/eleves','/admin/parents','/admin/rattachements/demandes','/admin/rattachements/demandes/opaque']){assert.equal(canAccessPath(path,['ADMIN_GESTIONNAIRE']),true);assert.equal(canAccessPath(path,['PARENT']),false)}})
test('attachment requests support pagination, status and period filters',()=>{assert.match(service,/attachmentRequests/);assert.match(service,/AttachmentFilters/);assert.match(requests,/page,limit:10/);assert.match(requests,/filters\.status/);assert.match(requests,/filters\.from/);assert.match(requests,/filters\.to/)})
test('attachment detail always uses public_id',()=>{assert.match(app,/demandes\/:publicId/);assert.match(service,/attachmentRequest:\(schoolId:string,publicId:string\)/);assert.match(service,/encodeURIComponent\(publicId\)/);assert.doesNotMatch(requests,/request\.id\b/)})
test('approval, motivated refusal and duplicate-decision prevention are wired',()=>{assert.match(requests,/decideAttachment\(schoolId,publicId,'APPROUVE'/);assert.match(requests,/decideAttachment\(schoolId,publicId,'REFUSE',reason/);assert.match(requests,/!reason\.trim\(\)/);assert.match(requests,/Cette demande a déjà été traitée/);assert.match(requests,/disabled=\{busy/)})
test('approved attachment can be disabled after confirmation',()=>{assert.match(requests,/disableAttachment/);assert.match(requests,/confirm\('Désactiver ce rattachement/);assert.match(requests,/mode==='disable'/)})
test('attachment documents reject unsupported UI types and expose no fake download',()=>{assert.match(requests,/application\/pdf/);assert.match(requests,/image\/jpeg/);assert.match(requests,/image\/png/);assert.match(requests,/Téléchargement sécurisé bientôt disponible/);assert.doesNotMatch(requests,/href=\{doc\./)})
test('annual classes are loaded from API and student creation sends class public_id',()=>{const form=src('src/pages/admin/students/StudentForm.tsx');assert.match(service,/async classes/);assert.match(form,/adminParentalApi\.classes/);assert.match(form,/academic_year_class_id/);assert.match(form,/item\.public_id/);assert.doesNotMatch(form,/mock/i)})
test('parent invitation prepares and reissues without exposing token or password',()=>{const invitation=src('src/components/adminParental/InvitationPanel.tsx');assert.match(service,/prepareInvitation/);assert.match(invitation,/Réémettre l’invitation/);assert.match(invitation,/invalide automatiquement l’ancienne/);assert.doesNotMatch(invitation,/accessToken|registration_token|mot de passe temporaire/i)})
test('resource screens implement loading error empty and success states',()=>{const state=src('src/components/adminParental/ResourceState.tsx');assert.match(state,/if \(loading\)/);assert.match(state,/if \(error\)/);assert.match(state,/if \(empty\)/);assert.match(requests,/resource-success|setData/);assert.match(src('src/services/api.ts'),/requestId/)})
test('responsive CSS stacks filters and forms and controls table overflow',()=>{const css=src('src/components/adminParental/admin-resources.css');assert.match(css,/overflow:auto/);assert.match(css,/@media\(max-width:850px\)/);assert.match(css,/resource-toolbar\{align-items:stretch;flex-direction:column/);assert.match(css,/resource-form-grid,.resource-profile-grid\{grid-template-columns:1fr/ )})
test('no internal numeric resource route or browser token storage was introduced',()=>{assert.doesNotMatch(app,/demandes\/:id|eleves\/:id|parents\/:id/);const api=src('src/services/api.ts');assert.doesNotMatch(service,/localStorage|sessionStorage/);assert.match(api,/accessToken: string \| null/ )})
