import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
test('toutes les routes Parent sont protégées par le rôle PARENT',()=>{const app=read('src/App.tsx');assert.match(app,/ProtectedRoute allowedRoles=\{\['PARENT'\]\}/);for(const route of['/parent','/parent/enfants','/parent/notifications','/parent/profil'])assert.ok(app.includes(`path="${route}"`))});
test('les routes enfant utilisent uniquement le publicId opaque',()=>{const app=read('src/App.tsx');const api=read('src/services/parentApi.ts');assert.match(app,/enfants\/:publicId/);assert.doesNotMatch(app,/enfants\/:studentId/);assert.match(api,/encodeURIComponent\(publicId\)/)});
test('le journal bloque le futur et affiche seulement les cours validés',()=>{const api=read('src/services/parentApi.ts');const page=read('src/pages/parent/ParentJournalDetail.tsx');assert.match(api,/assertPastOrToday/);assert.match(page,/validation_status==='validated'/);assert.match(page,/disabled=\{!lessons.length\|\|saving\}/)});
test('le visa demande confirmation et empêche le double envoi',()=>{const page=read('src/pages/parent/ParentJournalDetail.tsx');assert.match(page,/window\.confirm/);assert.match(page,/saving\|\|!lessons.length\|\|journal\?\.acknowledgement/);assert.match(page,/lesson_count_snapshot/)});
test('les notifications de paiement sont exclues',()=>{const page=read('src/pages/parent/ParentNotifications.tsx');assert.match(page,/payment\|invoice\|billing\|paiement\|factur/);assert.match(page,/filter\(item=>!excluded\(item\)\)/)});
test('le portail couvre loading erreur vide et le responsive',()=>{const state=read('src/components/parent/ParentState.tsx');const css=read('src/layouts/parent-layout.css');for(const name of['parent-loading','parent-error','parent-empty'])assert.ok(state.includes(name));for(const width of['1024','768','375'])assert.ok(css.includes(`max-width:${width}px`));assert.match(css,/overflow-x:hidden/)});
test('la navigation exclut paiements résultats et documents',()=>{const nav=read('src/components/parent/ParentNavigation.tsx');assert.doesNotMatch(nav,/paiement|facturation|résultat|bulletin|document/i)});
