import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiError, apiErrorMessage } from '../../services/api'
import { geographyApi, type GeographyItem } from '../../services/geography'
import { clearSchoolWizardSnapshot, loadSchoolWizardSnapshot, saveSchoolWizardSnapshot, schoolOnboardingApi, type SchoolOnboardingData, type SubscriptionOption } from '../../services/schoolOnboarding'
import { PHONE_CONFLICT_MESSAGE, phoneIdentityApi } from '../../services/phoneIdentity'

const schoolTypes = ['Complexe scolaire', 'Collège', 'Lycée', 'Groupe scolaire', 'Institut', 'E.P', 'E.P 1', 'E.P 2', 'E.P 3']
const steps = ['Informations école', 'Responsable', 'Configuration scolaire', 'Abonnement & paiement', 'Compte école']
const OTHER = '__other__'
const initialData: SchoolOnboardingData = {
  school:{name:'',school_type:'',phone:'',email:'',address:'',province_id:'',city_id:'',commune_id:'',neighborhood_id:'',geographic_reference:''},
  responsible:{first_name:'',last_name:'',birth_date:'',email:'',phone:''}, academic:{year_name:'',start_date:'',end_date:'',teacher_limit:1,parental_enabled:false},
  subscription:{subscription_code:'',billing_period:'monthly'}, account:{first_name:'',last_name:'',email:'',phone:'',password:''},
}

function choices(items:GeographyItem[],placeholder:string,other=false){return <><option value="">{placeholder}</option>{items.map(item=><option key={item.public_id} value={item.public_id}>{item.name}</option>)}{other&&<option value={OTHER}>Autre</option>}</>}
const emailOk=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)

/** Assistant unique : l'état reste monté lors des retours et la finalisation est idempotente côté API. */
export function NewSchoolFlow(){
  const restored=loadSchoolWizardSnapshot(),navigate=useNavigate()
  const[step,setStep]=useState(restored?.step??1),[data,setData]=useState<SchoolOnboardingData>(()=>restored?{school:{...initialData.school,...restored.data.school},responsible:{...initialData.responsible,...restored.data.responsible},academic:{...initialData.academic,...restored.data.academic},subscription:{...initialData.subscription,...restored.data.subscription},account:{...initialData.account,...restored.data.account,password:''}}:initialData),[draftId,setDraftId]=useState<string|null>(restored?.draftId??null)
  const[provinces,setProvinces]=useState<GeographyItem[]>([]),[cities,setCities]=useState<GeographyItem[]>([]),[communes,setCommunes]=useState<GeographyItem[]>([]),[neighborhoods,setNeighborhoods]=useState<GeographyItem[]>([])
  const[subscriptions,setSubscriptions]=useState<SubscriptionOption[]>([]),[errors,setErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const[other,setOther]=useState({city:'',commune:'',neighborhood:''})
  useEffect(()=>{Promise.all([geographyApi.provinces(),schoolOnboardingApi.subscriptions()]).then(async([geo,catalog])=>{setProvinces(geo.items);setSubscriptions(catalog.items);if(data.school.province_id)setCities((await geographyApi.cities(data.school.province_id)).items);if(data.school.city_id)setCommunes((await geographyApi.communes(data.school.city_id)).items);if(data.school.commune_id)setNeighborhoods((await geographyApi.neighborhoods(data.school.commune_id)).items)}).catch(error=>setMessage(apiErrorMessage(error)))},[])
  useEffect(()=>{saveSchoolWizardSnapshot({step,draftId,data})},[step,draftId,data])
  const update=<K extends keyof SchoolOnboardingData>(group:K,key:string,value:string|number|boolean)=>setData(current=>({...current,[group]:{...current[group],[key]:value}}))
  const field=(group:keyof SchoolOnboardingData,key:string)=>({value:String((data[group] as Record<string,unknown>)[key]??''),onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>{update(group,key,event.target.type==='number'?Number(event.target.value):event.target.value);setErrors(current=>({...current,[`${group}.${key}`]:''}))},className:errors[`${group}.${key}`]?'invalid':''})
  const err=(key:string)=>errors[key]&&<small className="field-error">{errors[key]}</small>

  function validate(current=step){const next:Record<string,string>={};const required=(group:keyof SchoolOnboardingData,keys:string[])=>keys.forEach(key=>{if(!String((data[group]as Record<string,unknown>)[key]??'').trim())next[`${group}.${key}`]='Champ obligatoire'})
    if(current===1){required('school',['name','school_type','phone','email','address','province_id','city_id','commune_id']);if(data.school.email&&!emailOk(data.school.email))next['school.email']='Adresse e-mail invalide'}
    if(current===2){required('responsible',['first_name','last_name','birth_date','email']);if(data.responsible.email&&!emailOk(data.responsible.email))next['responsible.email']='Adresse e-mail invalide'
      if(data.responsible.birth_date){const birth=new Date(`${data.responsible.birth_date}T00:00:00.000Z`),today=new Date(),limit=new Date(Date.UTC(today.getUTCFullYear()-18,today.getUTCMonth(),today.getUTCDate()));if(birth>limit)next['responsible.birth_date']='Le responsable doit être âgé d’au moins 18 ans.'}}
    if(current===3){required('academic',['year_name','start_date','end_date']);if(data.academic.start_date&&data.academic.end_date&&data.academic.end_date<=data.academic.start_date)next['academic.end_date']='La fin doit suivre le début'}
    if(current===4){required('subscription',['subscription_code','billing_period']);const plan=subscriptions.find(item=>item.code===data.subscription.subscription_code);if(plan&&data.academic.teacher_limit<plan.min_teachers)next['academic.teacher_limit']=`Minimum : ${plan.min_teachers}`}
    if(current===5){required('account',['first_name','last_name','email','phone','password']);if(data.account.email&&!emailOk(data.account.email))next['account.email']='Adresse e-mail invalide';if(data.account.password.length<10)next['account.password']='10 caractères minimum'}
    setErrors(next);if(Object.keys(next).length)setMessage('Corrigez les champs signalés avant de continuer.');return Object.keys(next).length===0}
  function backendError(error:unknown){if(error instanceof ApiError&&error.validationErrors.length){const fields:Record<string,string>={};for(const issue of error.validationErrors){const key=issue.field.replace(/^data\./,'');fields[key]=issue.code==='invalid_format'?'Format invalide':'Valeur invalide'}setErrors(fields)}setMessage(apiErrorMessage(error))}
  async function saveDraft(){setBusy(true);setMessage('');try{const response=await schoolOnboardingApi.saveDraft(draftId,step,data);setDraftId(response.draft.public_id);return response.draft.public_id}catch(error){backendError(error);return null}finally{setBusy(false)}}
  async function verifyPersonPhone(group:'responsible'|'account'){
    const person=data[group],phone=person.phone
    if(!phone)return true
    try{
      const result=await phoneIdentityApi.check({phone,first_name:person.first_name,last_name:person.last_name})
      update(group,'phone',result.normalized_phone)
      if(result.status==='CONFLICT'){setErrors(current=>({...current,[`${group}.phone`]:PHONE_CONFLICT_MESSAGE}));setMessage(PHONE_CONFLICT_MESSAGE);return false}
      if(result.status==='REUSE_ACCOUNT'){setMessage(`Un compte existe déjà pour ${result.person?.first_name||''} ${result.person?.last_name||''}. Sélectionnez cette personne existante au lieu de créer un doublon.`);return false}
      if(result.status==='CONTACT_WITHOUT_ACCOUNT')return window.confirm(`Ce numéro correspond à un contact sans compte (${result.person?.first_name||''} ${result.person?.last_name||''}). Confirmer sa réutilisation ?`)
      return true
    }catch(error){backendError(error);return false}
  }
  async function next(){if(!validate())return;if(step===2&&!await verifyPersonPhone('responsible'))return;if(step===5&&!await verifyPersonPhone('account'))return;if(step<5){const saved=await saveDraft();if(!saved)return;setStep(value=>value+1);setMessage('');return}const id=draftId||await saveDraft();if(!id)return;setBusy(true);try{const response=await schoolOnboardingApi.finalize(id,data);clearSchoolWizardSnapshot();navigate(`/management/ecoles?created=${encodeURIComponent(response.school.public_id)}`,{replace:true})}catch(error){backendError(error)}finally{setBusy(false)}}
  function cancel(){if(!window.confirm('Annuler la création et supprimer la sauvegarde interne ?'))return;clearSchoolWizardSnapshot();navigate('/management/ecoles')}
  async function province(value:string){update('school','province_id',value);update('school','city_id','');update('school','commune_id','');update('school','neighborhood_id','');setCities([]);setCommunes([]);setNeighborhoods([]);if(value)setCities((await geographyApi.cities(value)).items)}
  async function city(value:string){update('school','city_id',value);update('school','commune_id','');update('school','neighborhood_id','');setCommunes([]);setNeighborhoods([]);if(value&&value!==OTHER)setCommunes((await geographyApi.communes(value)).items)}
  async function commune(value:string){update('school','commune_id',value);update('school','neighborhood_id','');setNeighborhoods([]);if(value&&value!==OTHER)setNeighborhoods((await geographyApi.neighborhoods(value)).items)}
  async function addOther(kind:'city'|'commune'|'neighborhood'){setBusy(true);try{let item:GeographyItem;if(kind==='city'){item=(await geographyApi.addCity(data.school.province_id,other.city)).item;setCities(v=>[...v.filter(x=>x.public_id!==item.public_id),item]);update('school','city_id',item.public_id)}else if(kind==='commune'){item=(await geographyApi.addCommune(data.school.city_id,other.commune)).item;setCommunes(v=>[...v.filter(x=>x.public_id!==item.public_id),item]);update('school','commune_id',item.public_id)}else{item=(await geographyApi.addNeighborhood(data.school.commune_id,other.neighborhood)).item;setNeighborhoods(v=>[...v.filter(x=>x.public_id!==item.public_id),item]);update('school','neighborhood_id',item.public_id)}setOther(v=>({...v,[kind]:''}))}catch(error){setMessage(apiErrorMessage(error))}finally{setBusy(false)}}

  const selectedPlan=subscriptions.find(item=>item.code===data.subscription.subscription_code)
  function selectPlan(code:string){
    update('subscription','subscription_code',code)
    const plan=subscriptions.find(item=>item.code===code)
    if(!plan)return
    update('academic','teacher_limit',plan.code==='PROFESSIONAL'?Math.max(25,data.academic.teacher_limit):plan.configured_teacher_limit??plan.max_teachers??plan.min_teachers)
    if(!plan.billing_periods.includes(data.subscription.billing_period))update('subscription','billing_period',plan.billing_periods[0]||'monthly')
  }
  const input=(label:string,group:keyof SchoolOnboardingData,key:string,type='text',placeholder='')=><label>{label}<input type={type} placeholder={placeholder}{...field(group,key)}/>{err(`${group}.${key}`)}</label>
  return <section className="new-school-page"><section className="management-steps">{steps.map((name,index)=><article className={index+1===step?'active':index+1<step?'done':''} key={name}><b>{index+1}</b><span>{name}</span>{index<4&&<i/>}</article>)}</section>
    <section className="new-school-layout"><div className="management-card new-school-form"><h2>Étape {step}/5 - {steps[step-1]}</h2>{message&&<div className="wizard-message" role="status">{message}</div>}<div className="new-school-grid">
      {step===1&&<>{input("Nom de l'école *",'school','name')}
        <label>Type d'école *<select {...field('school','school_type')}><option value="">Sélectionner</option>{schoolTypes.map(type=><option key={type}>{type}</option>)}</select>{err('school.school_type')}</label>{input('Téléphone principal *','school','phone','tel')}{input("Email officiel de l'école *",'school','email','email')}{input('Adresse *','school','address','text','Avenue & Numéro de la parcelle')}
        <label>Province *<select value={data.school.province_id} className={errors['school.province_id']?'invalid':''} onChange={e=>void province(e.target.value)}>{choices(provinces,'Province...')}</select>{err('school.province_id')}</label>
        <label>Ville *<select value={data.school.city_id} className={errors['school.city_id']?'invalid':''} disabled={!data.school.province_id} onChange={e=>void city(e.target.value)}>{choices(cities,'Ville...',true)}</select>{err('school.city_id')}</label>{data.school.city_id===OTHER&&<label>Autre ville<div className="geo-other"><input value={other.city} onChange={e=>setOther(v=>({...v,city:e.target.value}))}/><button type="button" disabled={!other.city.trim()||busy} onClick={()=>void addOther('city')}>Ajouter</button></div></label>}
        <label>Commune *<select value={data.school.commune_id} className={errors['school.commune_id']?'invalid':''} disabled={!data.school.city_id||data.school.city_id===OTHER} onChange={e=>void commune(e.target.value)}>{choices(communes,'Commune...',true)}</select>{err('school.commune_id')}</label>{data.school.commune_id===OTHER&&<label>Autre commune<div className="geo-other"><input value={other.commune} onChange={e=>setOther(v=>({...v,commune:e.target.value}))}/><button type="button" disabled={!other.commune.trim()||busy} onClick={()=>void addOther('commune')}>Ajouter</button></div></label>}
        <label>Quartier<select value={data.school.neighborhood_id} disabled={!data.school.commune_id||data.school.commune_id===OTHER} onChange={e=>update('school','neighborhood_id',e.target.value)}>{choices(neighborhoods,'Quartier...',true)}</select></label>{data.school.neighborhood_id===OTHER&&<label>Autre quartier<div className="geo-other"><input value={other.neighborhood} onChange={e=>setOther(v=>({...v,neighborhood:e.target.value}))}/><button type="button" disabled={!other.neighborhood.trim()||busy} onClick={()=>void addOther('neighborhood')}>Ajouter</button></div></label>}{input('Référence géographique','school','geographic_reference')}</>}
      {step===2&&<>{input('Prénom du responsable *','responsible','first_name')}{input('Noms du responsable *','responsible','last_name')}{input('Date de naissance *','responsible','birth_date','date')}{input('E-mail *','responsible','email','email')}{input('Téléphone','responsible','phone','tel')}</>}
      {step===3&&<>{input('Année scolaire *','academic','year_name','text','2026-2027')}{input('Date de début *','academic','start_date','date')}{input('Date de fin *','academic','end_date','date')}<div className="wide module-choice"><strong>Modules activés</strong><label><input type="checkbox" checked disabled/> Contrôle pédagogique — obligatoire</label><label><input type="checkbox" checked={data.academic.parental_enabled} onChange={event=>update('academic','parental_enabled',event.target.checked)}/> Suivi parental — facultatif</label></div></>}
      {step===4&&<><label>Formule d'abonnement *<select value={data.subscription.subscription_code} onChange={event=>selectPlan(event.target.value)}><option value="">Sélectionner</option>{subscriptions.map(item=><option key={item.code} value={item.code}>{item.name} — {item.trial_days?`${item.trial_days} jours`: `${item.monthly_price} USD / mois`}</option>)}</select>{err('subscription.subscription_code')}</label><label>Période *<select {...field('subscription','billing_period')}>{(selectedPlan?.billing_periods||['monthly']).map(period=><option key={period} value={period}>{period==='monthly'?'Mensuelle':period==='quarterly'?'Trimestrielle':'Annuelle'}</option>)}</select></label>{selectedPlan&&<label>Quota enseignants *<input type="number" min={selectedPlan.code==='PROFESSIONAL'?25:undefined} value={data.academic.teacher_limit} readOnly={selectedPlan.code!=='PROFESSIONAL'} onChange={event=>update('academic','teacher_limit',Number(event.target.value))}/>{err('academic.teacher_limit')}</label>}{selectedPlan&&<div className="wide wizard-summary"><strong>{selectedPlan.name}</strong><span>Quota autorisé : {data.academic.teacher_limit} enseignant(s)</span><span>Aucune remise automatique appliquée.</span></div>}</>}
      {step===5&&<>{input('Prénom Admin *','account','first_name')}{input('Noms Admin *','account','last_name')}{input('E-mail de connexion *','account','email','email')}{input('Téléphone','account','phone','tel')}{input('Mot de passe initial *','account','password','password')}<div className="wide wizard-summary"><strong>Vérification finale</strong><span>{data.school.name}</span><span>{data.responsible.first_name} {data.responsible.last_name}</span><span>{data.academic.year_name} · {data.academic.teacher_limit} enseignant(s)</span></div></>}
    </div></div></section><div className="new-school-actions"><button className="wizard-button wizard-cancel" type="button" onClick={cancel}>Annuler</button>{step>1&&<button type="button" className="wizard-button wizard-previous" onClick={()=>setStep(value=>value-1)}>Précédent</button>}<button type="button" className={`wizard-button ${step===5?'wizard-create':'wizard-next'}`} disabled={busy} onClick={()=>void next()}>{busy?'Traitement…':step===5?"Créer l'école":'Suivant'}</button></div>
  </section>}
