import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../../../auth'
import { apiErrorMessage } from '../../../services/api'
import { adminParentalApi, type AttachmentRequest, type AttachmentStatus, type Page } from '../../../services/adminParental'
import { PageHeader } from '../../../components/adminParental/PageHeader'
import { ResourceState } from '../../../components/adminParental/ResourceState'
import { StatusBadge } from '../../../components/adminParental/StatusBadge'

const labels: Record<AttachmentStatus,string> = { BROUILLON:'Brouillon', EN_ATTENTE:'En attente', APPROUVE:'Approuvé', REFUSE:'Refusé', DESACTIVE:'Désactivé' }
const label = (status: AttachmentStatus) => labels[status] || status

/** Liste paginée : tous les critères restent côté API et l'URL ne contient aucun identifiant interne. */
export function AttachmentRequestsPage() {
  const { user } = useAuth(); const schoolId = user?.school_id
  const [result,setResult]=useState<Page<AttachmentRequest>|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [page,setPage]=useState(1)
  const [filters,setFilters]=useState<{search:string;status:''|AttachmentStatus;from:string;to:string}>({search:'',status:'',from:'',to:''})
  const load=()=>{if(!schoolId)return;setLoading(true);setError('');void adminParentalApi.attachmentRequests(schoolId,{...filters,status:filters.status||undefined,page,limit:10}).then(setResult).catch(e=>setError(apiErrorMessage(e))).finally(()=>setLoading(false))}
  useEffect(load,[schoolId,page])
  const counts=(status:AttachmentStatus)=>result?.items.filter(item=>item.status===status).length??0
  return <><PageHeader icon="⇄" title="Demandes d’attachement des parents à leurs enfants" subtitle="Consultez et gérez les demandes envoyées par les parents."/>
    <section className="admin-kpis"><article className="admin-card admin-kpi"><span>Total demandes</span><strong>{result?.total??'—'}</strong><small>Toutes périodes</small></article><article className="admin-card admin-kpi"><span>En attente sur cette page</span><strong>{counts('EN_ATTENTE')}</strong><small>À examiner</small></article><article className="admin-card admin-kpi"><span>Approuvées</span><strong>{counts('APPROUVE')}</strong><small>Page actuelle</small></article><article className="admin-card admin-kpi"><span>Refusées</span><strong>{counts('REFUSE')}</strong><small>Page actuelle</small></article></section>
    <section className="admin-card" style={{marginTop:14}}><form className="resource-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);load()}}><label>Parent ou élève<input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Rechercher par nom"/></label><label>Statut<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value as ''|AttachmentStatus})}><option value="">Tous</option>{Object.entries(labels).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label><label>Du<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Au<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><button className="admin-button">Filtrer</button></form>
    <ResourceState loading={loading} error={error} empty={!loading&&!error&&!result?.items.length} retry={load}><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>N°</th><th>Parent / tuteur</th><th>Élève concerné</th><th>Date</th><th>Statut</th><th>Action</th></tr></thead><tbody>{result?.items.map(item=><tr key={item.public_id}><td>{item.request_code}</td><td><b>{item.guardian.first_name} {item.guardian.last_name}</b></td><td>{item.student.first_name} {item.student.last_name}<small>{item.student.matricule}</small></td><td>{new Date(item.submitted_at).toLocaleDateString('fr-FR')}</td><td><StatusBadge status={label(item.status)}/></td><td><div className="resource-actions"><Link to={`/admin/rattachements/demandes/${item.public_id}`}>Consulter</Link></div></td></tr>)}</tbody></table></div>{result&&<footer className="resource-pagination"><span>{result.total} demande(s) · page {result.page}/{Math.max(result.pages,1)}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><button className="active">{page}</button><button disabled={page>=result.pages} onClick={()=>setPage(p=>p+1)}>›</button></div></footer>}</ResourceState></section></>
}

export function AttachmentRequestDetailPage() {
 const {publicId}=useParams(); const {user}=useAuth(); const schoolId=user?.school_id; const [data,setData]=useState<AttachmentRequest|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [mode,setMode]=useState<'refuse'|'disable'|null>(null); const [reason,setReason]=useState(''); const [document,setDocument]=useState({document_type:'identity',file_name:'',mime_type:'application/pdf',file_size:'',file_url:'',storage_key:''})
 const load=()=>{if(!schoolId||!publicId)return;setLoading(true);setError('');void adminParentalApi.attachmentRequest(schoolId,publicId).then(r=>setData(r.request)).catch(e=>setError(apiErrorMessage(e))).finally(()=>setLoading(false))};useEffect(load,[schoolId,publicId]);
 const approve=async()=>{if(!schoolId||!publicId||busy||!confirm('Approuver cette demande et activer le rattachement ?'))return;setBusy(true);try{setData((await adminParentalApi.decideAttachment(schoolId,publicId,'APPROUVE')).request)}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}}
 const submitReason=async()=>{if(!schoolId||!publicId||!mode||busy)return;if(!reason.trim()){setError('Un motif est obligatoire.');return}if(mode==='disable'&&!confirm('Désactiver ce rattachement sans supprimer son historique ?'))return;setBusy(true);try{setData((mode==='refuse'?await adminParentalApi.decideAttachment(schoolId,publicId,'REFUSE',reason):await adminParentalApi.disableAttachment(schoolId,publicId,reason)).request);setMode(null);setReason('')}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}}
 const addDocument=async(e:React.FormEvent)=>{e.preventDefault();if(!schoolId||!publicId||busy)return;const size=Number(document.file_size);if(!['application/pdf','image/jpeg','image/png'].includes(document.mime_type)){setError('Type interdit : seuls PDF, JPEG et PNG sont acceptés.');return}if(!Number.isFinite(size)||size<=0){setError('La taille déclarée est invalide.');return}setBusy(true);try{await adminParentalApi.addAttachmentDocument(schoolId,publicId,{...document,file_size:size,file_url:document.file_url||undefined,storage_key:document.storage_key||undefined});setDocument({...document,file_name:'',file_size:'',file_url:'',storage_key:''});load()}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}}
 const remove=async(documentId:string)=>{if(!schoolId||!publicId||busy||!confirm('Retirer ce justificatif de la demande ?'))return;setBusy(true);try{await adminParentalApi.removeAttachmentDocument(schoolId,publicId,documentId);load()}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}}
 const pending=data?.status==='EN_ATTENTE', approved=data?.status==='APPROUVE';return <><PageHeader icon="←" title="Détail et décision sur la demande d’attachement" subtitle="Vérifiez le parent, l’enfant et les justificatifs avant toute décision." back="/admin/rattachements/demandes"/><ResourceState loading={loading} error={!data?error:undefined} empty={!data} retry={load}>{data&&<><section className="admin-card resource-profile"><div className="resource-profile-grid"><section><h3>Demande</h3><p>{data.request_code}</p><StatusBadge status={label(data.status)}/><p>{new Date(data.submitted_at).toLocaleString('fr-FR')}</p></section><section><h3>Parent / tuteur</h3><p>{data.guardian.first_name} {data.guardian.last_name}</p><p>{data.guardian.phone||data.guardian.email||'Contact indisponible'}</p><p>Lien déclaré : {data.relationship_type}</p></section><section><h3>Élève</h3><p>{data.student.first_name} {data.student.last_name}</p><p>{data.student.matricule||'—'}</p></section></div></section>{error&&<div className="admin-error" style={{marginTop:14}}>{error}</div>}
 <section className="admin-card resource-form" style={{marginTop:14}}><h2>Justificatifs</h2>{!data.documents.length?<div className="resource-feedback">Aucun justificatif enregistré.</div>:<div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Type</th><th>Nom</th><th>Format</th><th>Taille</th><th>Statut</th><th>Action</th></tr></thead><tbody>{data.documents.map(doc=><tr key={doc.public_id}><td>{doc.document_type}</td><td>{doc.file_name}</td><td>{doc.mime_type}</td><td>{Math.ceil(Number(doc.file_size)/1024)} Ko</td><td><StatusBadge status="Disponible"/></td><td><button className="admin-button secondary" disabled={busy||!pending} onClick={()=>void remove(doc.public_id)}>Retirer</button></td></tr>)}</tbody></table></div>}<div className="resource-unavailable">Téléchargement sécurisé bientôt disponible. Aucun lien ou chemin de stockage n’est exposé.</div>{pending&&<form className="resource-form-grid" onSubmit={addDocument}><label>Type<select value={document.document_type} onChange={e=>setDocument({...document,document_type:e.target.value})}><option value="identity">Pièce d’identité</option><option value="parentage">Lien de parenté</option><option value="other">Autre</option></select></label><label>Nom du fichier<input value={document.file_name} onChange={e=>setDocument({...document,file_name:e.target.value})} required/></label><label>Format<select value={document.mime_type} onChange={e=>setDocument({...document,mime_type:e.target.value})}><option value="application/pdf">PDF</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label><label>Taille déclarée (octets)<input type="number" min="1" value={document.file_size} onChange={e=>setDocument({...document,file_size:e.target.value})} required/></label><label className="full">URL HTTPS ou clé de stockage externe<input value={document.file_url} onChange={e=>setDocument({...document,file_url:e.target.value})} placeholder="https://stockage-externe…" required/></label><button className="admin-button" disabled={busy}>Ajouter les métadonnées</button></form>}</section>
 <aside className="admin-card resource-form" style={{marginTop:14}}><h2>Prendre une décision</h2>{pending?<div className="admin-actions"><button className="admin-button green" disabled={busy} onClick={()=>void approve()}>Approuver</button><button className="admin-button" disabled={busy} onClick={()=>setMode('refuse')}>Refuser avec motif</button></div>:approved?<button className="admin-button" disabled={busy} onClick={()=>setMode('disable')}>Désactiver le rattachement</button>:<p>Cette demande a déjà été traitée. Aucune deuxième décision n’est autorisée.</p>}{mode&&<div><label>Motif obligatoire<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label><div className="admin-actions"><button className="admin-button secondary" disabled={busy} onClick={()=>setMode(null)}>Annuler</button><button className="admin-button" disabled={busy||!reason.trim()} onClick={()=>void submitReason()}>{busy?'Envoi…':'Confirmer'}</button></div></div>}</aside></>}</ResourceState></>
}
